version: '3.8'
name: scoreflow2

services:
  api:
    image: scoreflow-api:latest 
    container_name: scoreflow-api
    build:
      context: .
      dockerfile: API/Dockerfile  
    ports:
      - "5000:5000" 
      - "5001:5001"
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=bd-scoreflow2.ck3s6m6iih2w.us-east-1.rds.amazonaws.com,1433;Database=scoreflow2;User Id=admin;Password=Triski2015;TrustServerCertificate=True
    networks:
      - scoreflow-network

networks:
  scoreflow-network:
    driver: bridge
