# Esta plantilla de AWS SAM se ha generado a partir de la configuración de su
# función. Si su función tiene uno o más desencadenadores, tenga en cuenta que los
# recursos de AWS asociados a estos desencadenadores no están completamente
# especificados en esta plantilla e incluyen valores de marcadores de posición.
# Abra esta plantilla en AWS Infrastructure Composer o en su IDE favorito y
# modifíquela para especificar una aplicación sin servidor con otros recursos de
# AWS.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.
Resources:
  ScoreFlowLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      ImageUri: >-
        970547341305.dkr.ecr.eu-west-3.amazonaws.com/scoreflow@sha256:3a81a1ecb21531f4579ad59ed70522eae654393bb0aa8c2dbb122422c1e6a132
      PackageType: Image
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:eu-west-3:970547341305:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:eu-west-3:970547341305:log-group:/aws/lambda/ScoreFlowLambda:*
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /scoreflow
            Method: GET
